# Версия синтаксиса Compose (обычно пишут 3 или 3.8)
version: '3.8'

# Сервисы — это наши контейнеры
services:
  
  # 1. Наша база данных PostgreSQL
  db:
    image: postgres:15-alpine # Берем готовый официальный образ из интернета
    restart: always # Если база упадет, Докер сам ее перезапустит
    environment: # Те самые "пропсы" для настройки базы
      POSTGRES_USER: alex
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: shortener_db
    ports:
      - "5432:5432" # Пробрасываем порт, чтобы ты мог подключиться к БД через DBeaver/DataGrip
    volumes:
      # Магия сохранения данных: связываем папку внутри БД с папкой на твоем компе
      - pgdata:/var/lib/postgresql/data 
      
      #используем этот вариант для наглядности чтобы видеть файл бд прям в проекте
      # Точка и слеш (./) означают "создай папку прямо здесь, рядом с docker-compose.yml"
      # - ./pgdata:/var/lib/postgresql/data

  # 2. Добавляем Redis
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"

  # 3. Наш Go-сервер
  app:
    build: . # Говорим: "Собери образ сам, используя Dockerfile в этой же папке"
    ports:
      - "5001:8080" # Тот самый проброс портов (Port Mapping)
    depends_on:
      - db # Сервер не начнет запускаться, пока не стартанет база
      - redis # Теперь ждем и базу, и редис
    environment:
      # Передаем нашему Go-коду строку для подключения к БД
      # Заметь: вместо IP-адреса мы используем имя сервиса "db"!
      DATABASE_URL: "postgres://alex:pass@db:5432/shortener_db?sslmode=disable"
      REDIS_URL: "redis:6379" # Имя сервиса из докера

# это пока закомменчено так как нам нужно увидеть файл бд в директории нашего проекта
# Объявляем том (Volume) для хранения файлов базы. 
volumes:
  pgdata: